version: '3.9'
services:
  dev:
    container_name: cryptomath-api-auth-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: npm run start:dev
    ports:
      - '5002:5002'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
  prod:
    container_name: cryptomath-api-auth-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '5002:5002'
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: cryptomath-api-auth-postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: